server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
    }

    location /health {
        access_log off;
        return 200 '{"status": "healthy", "service": "app"}';
        add_header Content-Type application/json;
    }

    location /api/ {
        # Proxy vers l'API (quand elle sera deployee)
        # proxy_pass http://api:3000/;
        return 200 '{"message": "API placeholder"}';
        add_header Content-Type application/json;
    }
}